### PR TITLE
Fix issue #71 & #78

### LINKED ISSUE #71: UI Web site: Update Wallet and fix logo of website
## Issue Overview

1. Update marquis wallet interface based on new design.
2. When search marquis on "google", it shows a white logo and repetitve domain 'xyz'.
image

### Wallet
- Implement design (new wallet dropdown - first part) [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3179-5274&node-type=section&t=wQYAxVCgHjbwNz9d-0).

### Google search result
- Use this [App-logo.zip](https://github.com/user-attachments/files/17771985/App-logo.zip) to update the logo
- Make sure the favicon work well on dark mode & light mode
- Replace `themarquis.xyz` with `The Marquis`

### PR DESCRIPTION
**Pull request by HungNDB**
# Resolve Issue
Fixes #71 & #78
## Types of change

- [x] Feature
- [x] Bug
- [x] Enhancement

### CODE REVIEW

File: packages/nextjs/app/brandkit/page.tsx [hunk 1]
```diff
@@ -231,60 +306,62 @@ function Page() {
             ))}
           </div>
           <div>
-            <div className="mb-[92px] text-[36px] text-gradient-2 text-[#00ECFF] font-bold font-arial">
+            <div className="sm:mb-[92px] mb-[50px] sm:text-[36px] text-[24px] text-gradient-2 text-[#00ECFF] font-bold font-arial">
```
Comment (Buuh2511) [inline packages/nextjs/app/brandkit/page.tsx:309]: Could u plse refactor this

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
Refactor mainly on [file ](packages/nextjs/app/brandkit/page.tsx)

**Review by Buuh2511 — APPROVED** [review]

**Comment by gianalarcon** [comment]
Thanks for your contribution @HungNDB! Please DM on discord: gianalarcon
